### ISSUE TITLE
Translation PT-BR

### ISSUE THREAD

**Issue by per-sa** [my-uol/uol-cs-docs#4]
# Translation to PT-BR (Brazilian Portuguese)

### TO-DO:

 - [ ] Translate all documentation
 - [ ] Translate navbar, sidebar, and other components
 - [ ] Translate links, resources and other useful informations

### Language Requisites:
- Brazilian Portuguese proficiency
- Follow grammar rules

### How to translate:

 1. Create a new branch with the convention `yourusername_langcode` (e.x: `per-sa_PT-BR`)
 2. Setup your directory just like this: On the folder **i18n**, create a folder with the i18n Language Code (e.x FR, PT-BR), create a new folder called `docusaurus-plugin-content-docs`, create a new folder called `current` and copy all files from the `docs` folder to the `current` folder:
 ```markdown
├── i18n
│   ├── i18n language code
│   │   ├── docusaurus-plugin-content-docs
│   │   │   ├── current
│   │   │   │   ├── docs content
```
 
![Image](https://github.com/my-uol/uol-cs-docs/assets/83146584/1f65668a-a0c0-4770-9a31-f765e5f5dd7c)

Make sure to always sync your branch with `develop`, commit significant changes and after you're done, create a **PR** (Pull Request) to `develop`.
